# Generated by Django 3.1.7 on 2021-05-03 02:35

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0002_auto_20210502_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='emailaddress',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_login',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=40),
        ),
    ]
